### ISSUE TITLE
Integration with Apollo?

### ISSUE THREAD

**Issue by danielkcz** [peterpme/apollo-tote#4]
Hi @peterpme. In [the article](https://dev-blog.apollodata.com/apollo-tote-declarative-patterns-and-a-sneak-peek-into-apollo-2-0-f23bd884943e) you have mentioned that this will appear in Apollo 2. Now when that's out, I cannot seem to find anything remotely similar there. Is it that well hidden or it's still under works? Where can I chime in, please?

**Comment by peterpme** [comment]
Hey @FredyC ! Are you on https://apollographql.slack.com?

Right now Apollo Tote works with 2.0 and lives in its own repo. That being said, this is something that can be discussed in slack :)

**Comment by danielkcz** [comment]
@peterpme Well, I am not there and apparently I need an invite since I don't have `@meteor.com` email :)

I was asking merely because Tote is a nice idea, but lacking mutation/subscriptions makes it only half useful. And just looking into [graphql HoC source](https://github.com/apollographql/react-apollo/blob/master/src/graphql.tsx) I cannot shake feeling there are so many things not covered by Tote...

**Comment by peterpme** [comment]
Apollo Tote: you are absolutely right! Tote was an experiment for me to get all this working and not interfering with Apollo's roadmap.

I personally haven't used subscriptions or mutations for this, but if you're interested in implementing it, I would be super happy & grateful to work with you!

Apollo Slack: https://www.apollographql.com/#slack you should be good after you click this :)

**Comment by peterpme** [comment]
@FredyC not sure if you'll get a notification ( i usually don't, lol )
